version: '2'
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8088:8088
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017